name: CI/CD for Main Branch

on:
  pull_request:
    branches:
      - main
      - canary
  push:
    branches:
      - main
      - canary

permissions:
  contents: write
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: false

      - name: Get Branch Names and Target Branch
        run: |
          echo "CLIENT_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV

          # Extract Server Branch Name from PR description
          SERVER_BRANCH=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=Server branch: )[^ ]+' || echo "default-branch")

          echo "Extracted SERVER_BRANCH: $SERVER_BRANCH"  # Debugging output
          echo "SERVER_BRANCH=${SERVER_BRANCH:-$CLIENT_BRANCH}" >> $GITHUB_ENV

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUTOTEST_ACTIONS }}" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 2222 89.23.4.133 >> ~/.ssh/known_hosts
          
      - name: Client Connect to server and perform Git operations
        run: |
          # Attempt SSH connection with debugging enabled
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 2222 npo@89.23.4.133 \
          "TARGET_BRANCH=${TARGET_BRANCH} CLIENT_BRANCH=${CLIENT_BRANCH} bash -c ' 
          set -x  
          echo \"✅ TARGET_BRANCH is: $TARGET_BRANCH\"
          echo \"✅ CLIENT_BRANCH is: $CLIENT_BRANCH\"
          
          cd ~/autodeploy-test || { echo \"❌ Failed to change directory\"; exit 1; }

          # **Remove existing repository completely**
          echo "⚠️ Removing existing repository..."
          rm -rf sep_erp_client || { echo "❌ Failed to remove old repo"; exit 1; }

          # **Clone a fresh copy of TARGET_BRANCH**
          echo "⚠️ Cloning fresh repository..."
          git clone --branch ${TARGET_BRANCH} git@github.com:NPO-Automotive/sep_erp_client.git || { echo "❌ Failed to clone repository"; exit 1; }
          cd sep_erp_client || { echo "❌ Failed to enter project directory"; exit 1; }
      
          # Fetch all branches
          git fetch --all || { echo "Failed to fetch branches"; exit 1; }

          # Switch to main/canary branch
          git checkout ${TARGET_BRANCH} || { echo "Failed to checkout ${TARGET_BRANCH}"; exit 1; }

          # Switch to CLIENT_BRANCH or create from remote
          if git checkout ${CLIENT_BRANCH}; then
            echo "Switched to existing branch '${CLIENT_BRANCH}'."
          else
            echo "'${CLIENT_BRANCH}' does not exist locally. Creating from remote."
            git checkout -b ${CLIENT_BRANCH} origin/${CLIENT_BRANCH} || { echo "Failed to create branch ${CLIENT_BRANCH}"; exit 1; }
          fi

          # Pull latest changes into CLIENT_BRANCH
          git pull origin ${CLIENT_BRANCH} || { echo "Failed to pull ${CLIENT_BRANCH}"; exit 1; }

          # Switch back to TARGET_BRANCH
          git checkout ${TARGET_BRANCH} || { echo "Failed to checkout ${TARGET_BRANCH}"; exit 1; }

          # Set Git User
          git config --global user.email "rgjoyce111@gmail.com"
          git config --global user.name "atomant1969"

          # Merge CLIENT_BRANCH into TARGET_BRANCH without committing
          git merge ${CLIENT_BRANCH} --no-commit || { echo "Failed to merge ${CLIENT_BRANCH} into ${TARGET_BRANCH}"; exit 1; }

          # Check pnpm installation
          echo "Checking pnpm version:"
          pnpm --version

          # Build site
          pnpm i || { echo "Failed to install dependencies"; exit 1; }
          pnpm run build || { echo "Failed to build site"; exit 1; }
          rsync -av build/ dist/ || { echo "Failed to sync build to dist"; exit 1; }
          '"

      - name: Server Connect and Perform Git Operations
        run: |
          # Attempt SSH connection with debugging enabled
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 2222 npo@89.23.4.133 \
          "TARGET_BRANCH=${TARGET_BRANCH} SERVER_BRANCH=${SERVER_BRANCH} bash -c ' 
          set -x  
          echo \"✅ TARGET_BRANCH is: $TARGET_BRANCH\"
          echo \"✅ SERVER_BRANCH is: $SERVER_BRANCH\"
          
          docker cp /home/npo/.ssh/id_rsa sep-erp-test_app_test_1:/root/.ssh/id_rsa
          docker cp /home/npo/.ssh/id_rsa.pub sep-erp-test_app_test_1:/root/.ssh/id_rsa.pub

          docker exec -e TARGET_BRANCH=\"$TARGET_BRANCH\" -e SERVER_BRANCH=\"$SERVER_BRANCH\" sep-erp-test_app_test_1 bash -c \"set -e;
          
          apt-get update && apt-get install -y openssh-client
          chmod 600 /root/.ssh/id_rsa
          chmod 644 /root/.ssh/id_rsa.pub

          # Add GitHub to known hosts
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo \\\"✅ SSH Key Setup Complete Inside Docker!\\\";
         
          echo \\\"📌 [START] Fetching branches for SERVER_BRANCH: \$SERVER_BRANCH on TARGET_BRANCH: \$TARGET_BRANCH\\\";

          echo \\\"🔹 TARGET_BRANCH is: \$TARGET_BRANCH\\\";
          echo \\\"🔹 SERVER_BRANCH is: \$SERVER_BRANCH\\\";

          # install git if it is missing
          apt update && apt install -y git

          git fetch --all || { echo \\\"❌ Failed to fetch branches\\\"; exit 1; }
          git reset --hard origin/\$TARGET_BRANCH || { echo \\\"❌ Failed to reset TARGET_BRANCH\\\"; exit 1; }
          git switch \$TARGET_BRANCH || { echo \\\"❌ Failed to switch to TARGET_BRANCH\\\"; exit 1; }

          if [ \"\\$SERVER_BRANCH\" != \"default-branch\" ]; then
            # Ensure the local SERVER_BRANCH is deleted before pulling from remote
            if git show-ref --verify --quiet refs/heads/\$SERVER_BRANCH; then
              git branch -D \$SERVER_BRANCH || echo \\\"✅ No existing local branch \$SERVER_BRANCH, skipping deletion.\\\"
            else
              echo \\\"✅ No existing local branch \$SERVER_BRANCH, skipping deletion.\\\"
            fi

            git pull origin \$TARGET_BRANCH || { echo \\\"❌ Failed to pull TARGET_BRANCH\\\"; exit 1; }

            # Force reset instead of pull to avoid fast-forward issues
            git fetch origin \$SERVER_BRANCH || { echo \\\"❌ Failed to fetch SERVER_BRANCH\\\"; exit 1; }
            git reset --hard origin/\$SERVER_BRANCH || { echo \\\"❌ Failed to reset SERVER_BRANCH\\\"; exit 1; }
            
            # ✅ **Merge SERVER_BRANCH into TARGET_BRANCH**
            git checkout \\$TARGET_BRANCH || { echo \\\"❌ Failed to switch back to TARGET_BRANCH\\\"; exit 1; }
            git pull
            git merge --no-commit --no-ff origin/\\$SERVER_BRANCH || { echo \\\"❌ Failed to merge SERVER_BRANCH into TARGET_BRANCH\\\"; exit 1; }
          fi
          # Install TypeScript globally
          #npm install -g typescript
          
          # Install dependencies before building
          #pnpm add sequelize @types/sequelize --filter ./packages/zod-shared || { echo \\\"❌ Failed to install dependencies\\\"; exit 1; }

          # Verify TypeScript availability
          #tsc -v || { echo \\\"❌ TypeScript is still missing!\\\"; exit 1; }
          
          pnpm i || { echo \\\"❌ Failed to install dependencies\\\"; exit 1; }
          pnpm run build:lib || { echo \\\"❌ Failed to build site libraries\\\"; exit 1; }
          pnpm run build || { echo \\\"❌ Failed to build site\\\"; exit 1; }
          
          echo \\\"📌 [COMPLETE] Server operations finished successfully!\\\";
          \" ' || { echo \"❌ Docker exec command failed\"; exit 1; }


          echo \\\"🔄 Restarting Docker container...\\\"
          docker restart sep-erp-test_app_test_1 2>&1 | tee /tmp/docker_restart.log || { echo \"❌ Failed to restart Docker container\"; cat /tmp/docker_restart.log; exit 1; }
          "


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'
          cache: 'npm'

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
            playwright-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright dependencies
        run: sudo npx playwright install-deps

      - name: Install Playwright browsers
        run: npx playwright install
        
      
      - name: Run Playwright tests with xvfb
        env:
          TEST_DIR: '.'
          BASE_URL: 'http://test.pksep.ru/'
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npm run test

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: List the gh-pages directory
        if: always()      
        run: |
          ls -al gh-pages

      - name: Cerate allure reports folder if not exist
        if: always()
        run: |
          mkdir -p gh-pages
          mkdir -p gh-pages/allure-reports
          ls -al gh-pages

      - name: Ensure allure-reports exists
        if: always()
        run: |
          [ -d gh-pages/allure-reports ] || mkdir -p gh-pages/allure-reports

      - name: Copy Previous Reports to Allure Reports
        if: always()      
        run: |
          if [ -d gh-pages/allure-reports ]; then
            cp -r gh-pages/allure-reports/* allure-reports/ || echo "No previous reports found"
          fi

      - name: Debug Test Results Directory
        if: always()      
        run: ls -lah build/allure-results || echo "⚠️ No test results found"

      - name: Merge Historical Reports Before Generating New One
        if: always()
        run: |
          mkdir -p allure-reports
          cp -r build/allure-results/* allure-reports/ || echo "⚠️ No new test results found to append"

      - name: Build test report
        if: always()
        uses: simple-elf/allure-report-action@v1.7
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_history: allure-reports
          keep_reports: 20  # Keeps the last 20 test runs in history

      - name: Debug Allure Reports Before Publishing
        if: always()      
        run: ls -lah allure-reports || echo "⚠️ No reports found in allure-reports"

      - name: Update index.html to point to latest report
        if: always()      
        run: |
          LATEST_DIR=$(ls -td allure-reports/* | head -n 1)
          echo "<meta http-equiv='refresh' content='0; URL=${LATEST_DIR}/index.html'>" > allure-reports/index.html
          echo "<meta http-equiv='Cache-Control' content='no-cache, no-store, must-revalidate'>" >> allure-reports/index.html
          echo "<meta http-equiv='Pragma' content='no-cache'>" >> allure-reports/index.html
          echo "<meta http-equiv='Expires' content='0'>" >> allure-reports/index.html

      - name: Force GitHub Pages Refresh
        if: always()      
        run: |
          git commit --allow-empty -m "Trigger GitHub Pages rebuild"
          git push

      - name: Debug index.html Before Publishing
        if: always()      
        run: cat allure-reports/index.html

      - name: Fix Permissions Before Cleanup
        if: always()
        run: |
          sudo chmod -R 777 /home/runner/work/autotests/autotests/allure-reports/.git || echo "⚠️ Failed to change permissions"
          rm -rf /home/runner/work/autotests/autotests/allure-reports/.git || echo "⚠️ Failed to remove .git directory"

      - name: Debug Allure Reports Before Publishing
        run: ls -lah allure-reports

      - name: Publish Test Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-reports
          force_orphan: false  # Keeps previous data instead of wiping history

