
name: CI/CD for Main Branch

on:
  pull_request:
    branches:
      - main
      - canary
  push:
    branches:
      - main
      - canary

permissions:
  contents: write
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: false

      - name: Get Branch Names and Target Branch
        run: |
          echo "CLIENT_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV

          # Extract Server Branch Name from PR description
          SERVER_BRANCH=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=Server branch: )[^ ]+' || echo "default-branch")

          echo "Extracted SERVER_BRANCH: $SERVER_BRANCH"  # Debugging output
          echo "SERVER_BRANCH=${SERVER_BRANCH:-$CLIENT_BRANCH}" >> $GITHUB_ENV

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUTOTEST_ACTIONS }}" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 2222 89.23.4.133 >> ~/.ssh/known_hosts
          
      - name: Client Connect to server and perform Git operations
        run: |
          # Attempt SSH connection with debugging enabled
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 2222 npo@89.23.4.133 \
          "TARGET_BRANCH=${TARGET_BRANCH} CLIENT_BRANCH=${CLIENT_BRANCH} bash -c ' 
          set -x  
          echo \"✅ TARGET_BRANCH is: $TARGET_BRANCH\"
          echo \"✅ CLIENT_BRANCH is: $CLIENT_BRANCH\"
          cd ~/autodeploy-test/sep_erp_client || { echo \"❌ Failed to change directory\"; exit 1; }

          # Fetch all branches
          git fetch --all || { echo "Failed to fetch branches"; exit 1; }

          # Switch to main/canary branch
          git checkout ${TARGET_BRANCH} || { echo "Failed to checkout ${TARGET_BRANCH}"; exit 1; }

          # Switch to CLIENT_BRANCH or create from remote
          if git checkout ${CLIENT_BRANCH}; then
            echo "Switched to existing branch '${CLIENT_BRANCH}'."
          else
            echo "'${CLIENT_BRANCH}' does not exist locally. Creating from remote."
            git checkout -b ${CLIENT_BRANCH} origin/${CLIENT_BRANCH} || { echo "Failed to create branch ${CLIENT_BRANCH}"; exit 1; }
          fi

          # Pull latest changes into CLIENT_BRANCH
          git pull origin ${CLIENT_BRANCH} || { echo "Failed to pull ${CLIENT_BRANCH}"; exit 1; }

          # Switch back to TARGET_BRANCH
          git checkout ${TARGET_BRANCH} || { echo "Failed to checkout ${TARGET_BRANCH}"; exit 1; }

          # Set Git User
          git config --global user.email "rgjoyce111@gmail.com"
          git config --global user.name "atomant1969"

          # Merge CLIENT_BRANCH into TARGET_BRANCH without committing
          git merge ${CLIENT_BRANCH} --no-commit || { echo "Failed to merge ${CLIENT_BRANCH} into ${TARGET_BRANCH}"; exit 1; }

          # Check pnpm installation
          echo "Checking pnpm version:"
          pnpm --version

          # Build site
          pnpm i || { echo "Failed to install dependencies"; exit 1; }
          pnpm run build || { echo "Failed to build site"; exit 1; }
          rsync -av build/ dist/ || { echo "Failed to sync build to dist"; exit 1; }
          '"

      - name: Server Connect and Perform Git Operations
        run: |
          # Attempt SSH connection with debugging enabled
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 2222 npo@89.23.4.133 \
          "TARGET_BRANCH=${TARGET_BRANCH} SERVER_BRANCH=${SERVER_BRANCH} bash -c ' 
          set -x  

          docker exec -e TARGET_BRANCH=\"$TARGET_BRANCH\" -e SERVER_BRANCH=\"$SERVER_BRANCH\" sep-erp-test_app_test_1 bash -c \"set -e;

          git fetch --all || { echo \\\"❌ Failed to fetch branches\\\"; exit 1; }
          git reset --hard origin/\$TARGET_BRANCH || { echo \\\"❌ Failed to reset TARGET_BRANCH\\\"; exit 1; }
          git switch \$TARGET_BRANCH || { echo \\\"❌ Failed to switch to TARGET_BRANCH\\\"; exit 1; }

          # Ensure the local SERVER_BRANCH is deleted before pulling from remote
          if git show-ref --verify --quiet refs/heads/\$SERVER_BRANCH; then
            git branch -D \$SERVER_BRANCH || echo \\\"✅ No existing local branch \$SERVER_BRANCH, skipping deletion.\\\"
          else
            echo \\\"✅ No existing local branch \$SERVER_BRANCH, skipping deletion.\\\"
          fi
          \" ' || { echo \"❌ Docker exec command failed\"; exit 1; }

          '"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'
          cache: 'npm'

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
            playwright-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright dependencies
        run: sudo npx playwright install-deps

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests with xvfb
        env:
          TEST_DIR: '.'
          BASE_URL: 'http://dev.pksep.ru/'
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npm run test

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Create index.html
        if: always()
        run: |
          mkdir -p allure-history
          echo '<meta http-equiv="refresh" content="0; URL=./latest/index.html">' > allure-history/index.html

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.AUTOTEST_ACTIONS }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true

      - name: Cleanup
        if: always()
        run: |
          git config --global --unset safe.directory || true
          rm -rf .git/modules/* || true
