name: CI/CD for Main Branch

on:
  pull_request:
    branches:
      - CI-CD-Test-Main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.13.1'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright dependencies
        run: sudo npx playwright install-deps

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests with xvfb
        env:
          TEST_DIR: '.'
          BASE_URL: 'http://dev.npoamotiv.ru'
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npm run test

      - name: Generate Allure report
        if: always() # Ensure this step runs even if tests fail
        run: |
          npm install -g allure-commandline --save-dev
          allure generate --clean

      - name: List Allure report directory
        if: always() # Ensure this step runs even if tests fail
        run: ls -la allure-report

      - name: List current working directory
        if: always() # Ensure this step runs even if tests fail
        run: ls -la

      - name: Deploy Allure report to GitHub Pages
        if: always() # Ensure this step runs even if tests fail
        run: |
          npm install -g gh-pages
          gh-pages -d allure-report
