
name: CI/CD for Main Branch

on:
  pull_request:
    branches:
      - main
      - canary
  push:
    branches:
      - main
      - canary

permissions:
  contents: write
  pages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: false

      - name: Get Branch Names and Target Branch
        run: |
          echo "CLIENT_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV

          # Extract Server Branch Name from PR description
          SERVER_BRANCH=$(echo "${{ github.event.pull_request.body }}" | grep -oP '(?<=Server branch: )[^ ]+' || echo "default-branch")

          echo "Extracted SERVER_BRANCH: $SERVER_BRANCH"  # Debugging output
          echo "SERVER_BRANCH=${SERVER_BRANCH:-$CLIENT_BRANCH}" >> $GITHUB_ENV

      #- name: Add SSH host key
      #  run: |
      #    mkdir -p ~/.ssh
      #    ssh-keyscan -p 2222 89.23.4.133 >> ~/.ssh/known_hosts
      #    cat ~/.ssh/known_hosts
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AUTOTEST_ACTIONS }}" | sed 's/\\n/\n/g' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 2222 89.23.4.133 >> ~/.ssh/known_hosts
          
      - name: Client Connect to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 2222 npo@89.23.4.133 << 'EOF'
          set -x  # Enable debugging
          echo "✅ SSH session is running successfully!"
          pwd
          ls -la
          EOF


      - name: Client Connect to server and perform Git operations
        run: |
          #ssh-keyscan -p 2222 89.23.4.133 >> ~/.ssh/known_hosts
          #chmod 644 ~/.ssh/known_hosts

          #export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa"

          # Attempt SSH connection with debugging enabled
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -p 2222 npo@89.23.4.133 << "EOF"
          #ssh -o StrictHostKeyChecking=no  -i ~/.ssh/id_rsa -p 2222 npo@89.23.4.133 TARGET_BRANCH=${TARGET_BRANCH} CLIENT_BRANCH=${CLIENT_BRANCH} << "EOF"
          #ssh -t -o StrictHostKeyChecking=no -p 2222 npo@89.23.4.133 "TARGET_BRANCH=${TARGET_BRANCH} CLIENT_BRANCH=${CLIENT_BRANCH}" << "EOF"
          
          set -x  # Enable debugging
          TARGET_BRANCH="${TARGET_BRANCH}"
          CLIENT_BRANCH="${CLIENT_BRANCH}"

          export TARGET_BRANCH
          export CLIENT_BRANCH

          echo "✅ TARGET_BRANCH is: $TARGET_BRANCH"
          echo "✅ CLIENT_BRANCH is: $CLIENT_BRANCH"
          
          cd ~/autodeploy-test/sep_erp_client || { echo "Failed to change directory"; exit 1; }
          pwd
          ls -la
          # Fetch all branches
          git fetch --all || { echo "Failed to fetch branches"; exit 1; }

          # Switch to main/canary branch
          git checkout ${TARGET_BRANCH} || { echo "Failed to checkout ${TARGET_BRANCH}"; exit 1; }

          # Switch to CLIENT_BRANCH or create from remote
          if git checkout ${CLIENT_BRANCH}; then
            echo "Switched to existing branch '${CLIENT_BRANCH}'."
          else
            echo "'${CLIENT_BRANCH}' does not exist locally. Creating from remote."
            git checkout -b ${CLIENT_BRANCH} origin/${CLIENT_BRANCH} || { echo "Failed to create branch ${CLIENT_BRANCH}"; exit 1; }
          fi

          # Pull latest changes into CLIENT_BRANCH
          git pull origin ${CLIENT_BRANCH} || { echo "Failed to pull ${CLIENT_BRANCH}"; exit 1; }

          # Switch back to TARGET_BRANCH
          git checkout ${TARGET_BRANCH} || { echo "Failed to checkout ${TARGET_BRANCH}"; exit 1; }

          # Set Git User
          git config --global user.email "rgjoyce111@gmail.com"
          git config --global user.name "atomant1969"

          # Merge CLIENT_BRANCH into TARGET_BRANCH without committing
          git merge ${CLIENT_BRANCH} --no-commit || { echo "Failed to merge ${CLIENT_BRANCH} into ${TARGET_BRANCH}"; exit 1; }

          # Check current directory and contents
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la

          # Check pnpm installation
          echo "Checking pnpm version:"
          pnpm --version

          # Build site
          pnpm i || { echo "Failed to install dependencies"; exit 1; }
          pnpm run build || { echo "Failed to build site"; exit 1; }
          rsync -av build/ dist/ || { echo "Failed to sync build to dist"; exit 1; }
          EOF



      - name: Server Fetch All Branches for server
        run: |
          ssh -t -p 2222 npo@89.23.4.133 TARGET_BRANCH=${TARGET_BRANCH} SERVER_BRANCH=${SERVER_BRANCH} << "EOF"
          set -x  # Enable debugging

          docker exec -e TARGET_BRANCH=$TARGET_BRANCH -e SERVER_BRANCH=$SERVER_BRANCH sep-erp-test_app_test_1 bash -c "
          set -e  # Exit on error

          echo '📌 [START] Fetching branches for SERVER_BRANCH: \$SERVER_BRANCH on TARGET_BRANCH: \$TARGET_BRANCH'
    
          # Debug variable values
          echo '🔹 TARGET_BRANCH is:' \$TARGET_BRANCH
          echo '🔹 SERVER_BRANCH is:' \$SERVER_BRANCH

          echo '🔹 Fetching all branches...'
          git fetch --all 2>&1 | tee /tmp/git_fetch.log || { echo '❌ Failed to fetch branches'; cat /tmp/git_fetch.log; exit 1; }

          echo '🔹 Switching to TARGET_BRANCH: \$TARGET_BRANCH...'
          git switch \$TARGET_BRANCH 2>&1 | tee /tmp/git_switch.log || { echo '❌ Failed to switch to TARGET_BRANCH'; cat /tmp/git_switch.log; exit 1; }

          echo '🔹 Pulling latest changes for TARGET_BRANCH...'
          git pull origin \$TARGET_BRANCH 2>&1 | tee /tmp/git_pull_target.log || { echo '❌ Failed to pull TARGET_BRANCH'; cat /tmp/git_pull_target.log; exit 1; }

          echo '🔹 Pulling latest changes for SERVER_BRANCH...'
          git pull origin \$SERVER_BRANCH 2>&1 | tee /tmp/git_pull_server.log || { echo '❌ Failed to pull SERVER_BRANCH'; cat /tmp/git_pull_server.log; exit 1; }

          echo '🔹 Merging SERVER_BRANCH into TARGET_BRANCH...'
          git merge --no-commit --no-ff \$SERVER_BRANCH 2>&1 | tee /tmp/git_merge.log || { echo '❌ Failed to merge SERVER_BRANCH into TARGET_BRANCH'; cat /tmp/git_merge.log; exit 1; }

          echo '🔹 Installing dependencies...'
          pnpm i 2>&1 | tee /tmp/pnpm_install.log || { echo '❌ Failed to install dependencies'; cat /tmp/pnpm_install.log; exit 1; }

          echo '🔹 Building application...'
          pnpm run build 2>&1 | tee /tmp/pnpm_build.log || { echo '❌ Failed to build site'; cat /tmp/pnpm_build.log; exit 1; }

          echo '🔹 Syncing build files...'
          rsync -av build/ dist/ 2>&1 | tee /tmp/rsync.log || { echo '❌ Failed to sync build to dist'; cat /tmp/rsync.log; exit 1; }

          echo '📌 [COMPLETE] Server operations finished successfully!'

          " || { echo '❌ Docker exec command failed'; exit 1; }

          echo '🔄 Restarting Docker container...'
          docker restart sep-erp-test_app_test_1 2>&1 | tee /tmp/docker_restart.log || { echo '❌ Failed to restart Docker container'; cat /tmp/docker_restart.log; exit 1; }
          EOF


      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.13.1'
          cache: 'npm'

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            playwright-${{ runner.os }}-
            playwright-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright dependencies
        run: sudo npx playwright install-deps

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Run Playwright tests with xvfb
        env:
          TEST_DIR: '.'
          BASE_URL: 'http://dev.pksep.ru/'
        run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npm run test

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@master
        with:
          name: allure-results
          path: allure-results
          retention-days: 20

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          keep_reports: 20

      - name: Create index.html
        if: always()
        run: |
          mkdir -p allure-history
          echo '<meta http-equiv="refresh" content="0; URL=./latest/index.html">' > allure-history/index.html

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.AUTOTEST_ACTIONS }}
          publish_branch: gh-pages
          publish_dir: allure-history
          force_orphan: true

      - name: Cleanup
        if: always()
        run: |
          git config --global --unset safe.directory || true
          rm -rf .git/modules/* || true
